### ISSUE TITLE
Embelin // Webasto ThermoConnect API

### ISSUE THREAD

**Issue by Nornode** [zoukkinen/Homeassistant-conf#1]
Hi!
Just checking in:
Did you ever get anywhere with accessing the API to integrate into Home Assistant?

> Working with Embelin (Webasto ThermoConnect) to find out if they can open their API to control GSM/GPRS car heating systems via homeassistant.

This has been on my agenda for a while and would like to find some time to do something about it.

**Comment by Nornode** [comment]
Bump! 🙄

**Comment by zoukkinen** [comment]
They did eventually answer that they have no plans to make an open API for the public, so a no-go from their end.

**Comment by MTrab** [comment]
Sorry to awaken this OLD issue - but I think I have cracked the problems authenticating and are currently testing a python module I have developed, prior to writing the full integration for Home Assistant.
